export const ACTION_TYPE = {
	ADD_POST: 'ADD_POST',
	UPDATE_POST: 'UPDATE_POST',
	DELETE_POST: 'DELETE_POST',
	LOAD_POST: 'LOAD_POST',
	LOAD_REQUESTED: 'LOAD_REQUESTED',
	POST_REQUESTED_FAILED: 'POST_REQUESTED_FAILED',
};
